p8105_hw1_cj2793
================
Chenyu Jin
2024-09-12

# Problem 1

Firstly, we input the dataset:

``` r
data("penguins", package = "palmerpenguins")
```

Then, we give a short description of the penguins dataset:

1.  We should know the data in this dataset:

``` r
summary(penguins)
```

    ##       species          island    bill_length_mm  bill_depth_mm  
    ##  Adelie   :152   Biscoe   :168   Min.   :32.10   Min.   :13.10  
    ##  Chinstrap: 68   Dream    :124   1st Qu.:39.23   1st Qu.:15.60  
    ##  Gentoo   :124   Torgersen: 52   Median :44.45   Median :17.30  
    ##                                  Mean   :43.92   Mean   :17.15  
    ##                                  3rd Qu.:48.50   3rd Qu.:18.70  
    ##                                  Max.   :59.60   Max.   :21.50  
    ##                                  NA's   :2       NA's   :2      
    ##  flipper_length_mm  body_mass_g       sex           year     
    ##  Min.   :172.0     Min.   :2700   female:165   Min.   :2007  
    ##  1st Qu.:190.0     1st Qu.:3550   male  :168   1st Qu.:2007  
    ##  Median :197.0     Median :4050   NA's  : 11   Median :2008  
    ##  Mean   :200.9     Mean   :4202                Mean   :2008  
    ##  3rd Qu.:213.0     3rd Qu.:4750                3rd Qu.:2009  
    ##  Max.   :231.0     Max.   :6300                Max.   :2009  
    ##  NA's   :2         NA's   :2

According to the summary results, we know that there are 3 species of
penguins in our dataset and they live in 3 different island. This
dataset includes the bill length, bill depth, flipper length and body
mass of each penguin. There are 165 female penguins and 168 male
penguins. Unfortunately, 11 of them are unknown of sex. The data were
collected during 2007 to 2009.

2.  We should know the data size in this dataset:

``` r
nrow(penguins)
```

    ## [1] 344

``` r
ncol(penguins)
```

    ## [1] 8

According to the results, we know that we have 344 rows (observations)
and 8 column (variables) in our dataset.

3.  We should know the mean flipper length of the penguins in the
    dataset:

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   3.5.1     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.3     ✔ tidyr     1.3.1
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
flipper_length <-- pull(penguins, flipper_length_mm)
mean(pull(penguins, flipper_length_mm), na.rm = TRUE)
```

    ## [1] 200.9152

Because there is missing data in the dataset, we should use na.rm
argument in mean() function. According to the result, we know that the
mean flipper length of the penguins is 200.9152mm.

Next, we should make a scatterplot of flipper_length_mm (y) vs
bill_length_mm (x) and then save it.

``` r
library(ggplot2)

plot1 <- ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm, color = species)) + geom_point() + labs(title = "Scatterplot of Flipper Length vs Bill Length",
                    x = "Bill Length (mm)",
                    y = "Flipper Length (mm)")

ggsave("scatterplot flipper vs bill length.png", plot = plot1)
```

    ## Saving 7 x 5 in image

    ## Warning: Removed 2 rows containing missing values or values outside the scale range
    ## (`geom_point()`).

# Problem 2

Firstly, we create a data frame:

``` r
library(tidyverse)
set.seed(1)

normal_sample <- rnorm(10)
logical_vector <- normal_sample > 0
char_vector <- c("A", "B", "C", "D", "E", "F", "G", "H", "I", "J")
factor_vector <- factor(sample(c("L0", "L1", "L2"), 10, replace = TRUE))

df <- tibble(
  Normal_Sample = normal_sample,
  Logical_Vector = logical_vector,
  Char_Vector = char_vector,
  Factor_Vector = factor_vector
)
```

Then, we try to take the mean of each variable in your data frame:

``` r
mean(pull(df, Normal_Sample))
```

    ## [1] 0.1322028

``` r
mean(pull(df, Logical_Vector))
```

    ## [1] 0.6

``` r
mean(pull(df, Char_Vector))
```

    ## Warning in mean.default(pull(df, Char_Vector)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

``` r
mean(pull(df, Factor_Vector))
```

    ## Warning in mean.default(pull(df, Factor_Vector)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

We can see that: For Normal Sample: Mean can be calculated as 0.1322028;
For Logical Vector: Mean can be calculated as 0.6; For character Vector:
Mean cannot be calculated; For Factor Vector: Mean cannot be calculated.

Finally, we try to convert variables from one type to another:

``` r
logical_numeric <- as.numeric(pull(df, Logical_Vector))
char_numeric <- as.numeric(pull(df, Char_Vector))
factor_numeric <- as.numeric(pull(df, Factor_Vector))
```

Here, we can see that:

When we convert a logical vector to numeric, TRUE becomes 1 and FALSE
becomes 0; When we take the mean of a logical vector, it’s treated as a
numeric vector with 0 and 1. As a result, it works.

When we convert a character vector to numeric, it will produce NA
because characters cannot be meaningfully coerced into numeric values;
As a result, when we try to calculate the mean of character vector, it
does not work.

When we convert a factor vector to numeric each level of the factor is
represented by an integer (L0 = 1; L1 = 2; L2 = 3); When we calculate
the mean of a factor vector, it is calculating the integer which is not
actually the levels; As a result, it does not work.
